import { StyleSheet } from 'react-native';
import { LANE_WIDTH, PLAYER_SIZE, OBSTACLE_SIZE, COIN_SIZE } from '../constants/gameConstants';

export const gameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  background: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  lane: {
    position: 'absolute',
    width: LANE_WIDTH,
    height: '100%',
    borderRightWidth: 2,
    borderRightColor: '#FFE5EC',
    opacity: 0.3,
  },
  laneIndicators: {
    position: 'absolute',
    bottom: 120,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
  },
  laneIndicator: {
    width: 30,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 4,
  },
  laneIndicatorActive: {
    backgroundColor: '#FFD700',
    width: 50,
    height: 10,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  hud: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 10,
  },
  scoreText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  coinText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
    marginTop: 5,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  speedText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  skillDisplay: {
    position: 'absolute',
    top: 120,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 10,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  skillName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4CAF50',
    textAlign: 'center',
  },
  skillActive: {
    fontSize: 12,
    color: '#FFD700',
    marginTop: 5,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  shieldText: {
    fontSize: 14,
    color: '#00BCD4',
    marginTop: 5,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  highScoreIndicator: {
    position: 'absolute',
    top: 140,
    left: 20,
    backgroundColor: 'rgba(255,215,0,0.3)',
    padding: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  highScoreText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFD700',
  },
  player: {
    position: 'absolute',
    width: PLAYER_SIZE,
    height: PLAYER_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playerImage: {
    width: '100%',
    height: '100%',
  },
  playerEmoji: {
    fontSize: 50,
  },
  obstacle: {
    position: 'absolute',
    width: OBSTACLE_SIZE,
    height: OBSTACLE_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  obstacleEmoji: {
    fontSize: 50,
  },
  coin: {
    position: 'absolute',
    width: COIN_SIZE,
    height: COIN_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
    backgroundColor: 'rgba(255, 215, 0, 0.5)', // Tăng opacity để dễ thấy
    borderRadius: COIN_SIZE / 2,
    borderWidth: 3, // Viền dày hơn
    borderColor: '#FFD700',
    shadowColor: '#FFD700', // Thêm shadow để nổi bật
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
  },
  coinEmoji: {
    fontSize: 45, // Tăng kích thước emoji
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  controlsHint: {
    position: 'absolute',
    bottom: 30,
    width: '100%',
    alignItems: 'center',
  },
  hintText: {
    fontSize: 14,
    color: '#FFE5EC',
    opacity: 0.6,
  },
  newRecordOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 215, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  newRecordText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFD700',
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  newRecordSubtext: {
    fontSize: 20,
    color: '#FFF',
    marginTop: 10,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  confettiContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 99,
    pointerEvents: 'none',
  },
  confetti: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  reviveOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 200,
  },
  revivePopup: {
    backgroundColor: '#1a1a2e',
    borderRadius: 20,
    padding: 30,
    width: '85%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
  },
  reviveTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FF4444',
    marginBottom: 15,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
  },
  reviveScore: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#00FF88',
    marginBottom: 10,
  },
  reviveMessage: {
    fontSize: 20,
    color: '#FFF',
    marginBottom: 5,
    textAlign: 'center',
  },
  reviveWarning: {
    fontSize: 14,
    color: '#FFD700',
    marginBottom: 25,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  reviveButtons: {
    width: '100%',
    gap: 15,
  },
  reviveButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 15,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#66BB6A',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  reviveButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  skipButton: {
    backgroundColor: '#555',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 15,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#777',
  },
  skipButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#CCC',
  },
});
